spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baselineOnMigrate: true
  h2:
    console:
      enabled: false

server:
  port: 8091
