version: '3.0'
services:
  beeburger:
    container_name: beeburger
    build: ./bee-burger-backend
    ports:
      - 8091:8091
    depends_on:
      - db
    environment:
      DB_HOST: db
    command: ["/wait-for-it.sh", "db:3306", "--", "java", "-jar", "app.jar"]
  db:
    container_name: db
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: pos
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 123456
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "16543:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456