version: '3.0'
services:
  beeburger:
    container_name: beeburger
    build: .
    ports:
      - 8091:8091
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
    command: ["/wait-for-it.sh", "db:3306", "--", "java", "-jar", "app.jar"]
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pos
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: 123456
